export const GET_ERRORS = "GET_ERRORS";
export const GET_EXPENSES = "GET_EXPENSES";
export const GET_EXPENSE = "GET_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";